/*
 * generated by Xtext 2.13.0
 */
package org.xtext.unina.xdstm


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class XdstmStandaloneSetup extends XdstmStandaloneSetupGenerated {

	def static void doSetup() {
		new XdstmStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
