/*
 * generated by Xtext 2.13.0
 */
package org.xtext.unina.xdstmdata.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.unina.xdstmdata.ui.internal.XdstmdataActivator;

public class XdstmdataUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return XdstmdataActivator.getInstance().getInjector("org.xtext.unina.xdstmdata.Xdstmdata");
	}

}
