/*
 * generated by Xtext 2.13.0
 */
package org.xtext.unina.xdstmdata.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractXdstmdataScopeProvider extends DelegatingScopeProvider {
}
