/*
 * generated by Xtext 2.13.0
 */
package org.xtext.unina.xdstm.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.xtext.unina.xdstm.ui.internal.XdstmActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class XdstmExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(XdstmActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		XdstmActivator activator = XdstmActivator.getInstance();
		return activator != null ? activator.getInjector(XdstmActivator.ORG_XTEXT_UNINA_XDSTM_XDSTM) : null;
	}

}
