/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.prgmdl.dstmverifier.data.node;

import org.prgmdl.dstmverifier.data.analysis.*;

@SuppressWarnings("nls")
public final class AENameBasic extends PBasic
{
    private PENameUse _eNameUse_;

    public AENameBasic()
    {
        // Constructor
    }

    public AENameBasic(
        @SuppressWarnings("hiding") PENameUse _eNameUse_)
    {
        // Constructor
        setENameUse(_eNameUse_);

    }

    @Override
    public Object clone()
    {
        return new AENameBasic(
            cloneNode(this._eNameUse_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAENameBasic(this);
    }

    public PENameUse getENameUse()
    {
        return this._eNameUse_;
    }

    public void setENameUse(PENameUse node)
    {
        if(this._eNameUse_ != null)
        {
            this._eNameUse_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._eNameUse_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._eNameUse_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._eNameUse_ == child)
        {
            this._eNameUse_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._eNameUse_ == oldChild)
        {
            setENameUse((PENameUse) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
