/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.prgmdl.dstmverifier.data.node;

import org.prgmdl.dstmverifier.data.analysis.*;

@SuppressWarnings("nls")
public final class AIdentifierMachineName extends PMachineName
{
    private PExtSymbol _extSymbol_;

    public AIdentifierMachineName()
    {
        // Constructor
    }

    public AIdentifierMachineName(
        @SuppressWarnings("hiding") PExtSymbol _extSymbol_)
    {
        // Constructor
        setExtSymbol(_extSymbol_);

    }

    @Override
    public Object clone()
    {
        return new AIdentifierMachineName(
            cloneNode(this._extSymbol_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIdentifierMachineName(this);
    }

    public PExtSymbol getExtSymbol()
    {
        return this._extSymbol_;
    }

    public void setExtSymbol(PExtSymbol node)
    {
        if(this._extSymbol_ != null)
        {
            this._extSymbol_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._extSymbol_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._extSymbol_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._extSymbol_ == child)
        {
            this._extSymbol_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._extSymbol_ == oldChild)
        {
            setExtSymbol((PExtSymbol) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
