/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.prgmdl.dstmverifier.data.node;

import org.prgmdl.dstmverifier.data.analysis.*;

@SuppressWarnings("nls")
public final class AListsSimpleSimpletypeList extends PSimpletypeList
{
    private PSimpletypeList _simpletypeList_;
    private TComma _comma_;
    private PSimpletype _simpletype_;

    public AListsSimpleSimpletypeList()
    {
        // Constructor
    }

    public AListsSimpleSimpletypeList(
        @SuppressWarnings("hiding") PSimpletypeList _simpletypeList_,
        @SuppressWarnings("hiding") TComma _comma_,
        @SuppressWarnings("hiding") PSimpletype _simpletype_)
    {
        // Constructor
        setSimpletypeList(_simpletypeList_);

        setComma(_comma_);

        setSimpletype(_simpletype_);

    }

    @Override
    public Object clone()
    {
        return new AListsSimpleSimpletypeList(
            cloneNode(this._simpletypeList_),
            cloneNode(this._comma_),
            cloneNode(this._simpletype_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAListsSimpleSimpletypeList(this);
    }

    public PSimpletypeList getSimpletypeList()
    {
        return this._simpletypeList_;
    }

    public void setSimpletypeList(PSimpletypeList node)
    {
        if(this._simpletypeList_ != null)
        {
            this._simpletypeList_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._simpletypeList_ = node;
    }

    public TComma getComma()
    {
        return this._comma_;
    }

    public void setComma(TComma node)
    {
        if(this._comma_ != null)
        {
            this._comma_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comma_ = node;
    }

    public PSimpletype getSimpletype()
    {
        return this._simpletype_;
    }

    public void setSimpletype(PSimpletype node)
    {
        if(this._simpletype_ != null)
        {
            this._simpletype_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._simpletype_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._simpletypeList_)
            + toString(this._comma_)
            + toString(this._simpletype_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._simpletypeList_ == child)
        {
            this._simpletypeList_ = null;
            return;
        }

        if(this._comma_ == child)
        {
            this._comma_ = null;
            return;
        }

        if(this._simpletype_ == child)
        {
            this._simpletype_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._simpletypeList_ == oldChild)
        {
            setSimpletypeList((PSimpletypeList) newChild);
            return;
        }

        if(this._comma_ == oldChild)
        {
            setComma((TComma) newChild);
            return;
        }

        if(this._simpletype_ == oldChild)
        {
            setSimpletype((PSimpletype) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
