/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.prgmdl.dstmverifier.transition.trigger.node;

import org.prgmdl.dstmverifier.transition.trigger.analysis.*;

@SuppressWarnings("nls")
public final class AChantBasic extends PBasic
{
    private TChn _chn_;
    private TLBkt _lBkt_;
    private PDefined _defined_;
    private TRBkt _rBkt_;

    public AChantBasic()
    {
        // Constructor
    }

    public AChantBasic(
        @SuppressWarnings("hiding") TChn _chn_,
        @SuppressWarnings("hiding") TLBkt _lBkt_,
        @SuppressWarnings("hiding") PDefined _defined_,
        @SuppressWarnings("hiding") TRBkt _rBkt_)
    {
        // Constructor
        setChn(_chn_);

        setLBkt(_lBkt_);

        setDefined(_defined_);

        setRBkt(_rBkt_);

    }

    @Override
    public Object clone()
    {
        return new AChantBasic(
            cloneNode(this._chn_),
            cloneNode(this._lBkt_),
            cloneNode(this._defined_),
            cloneNode(this._rBkt_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAChantBasic(this);
    }

    public TChn getChn()
    {
        return this._chn_;
    }

    public void setChn(TChn node)
    {
        if(this._chn_ != null)
        {
            this._chn_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._chn_ = node;
    }

    public TLBkt getLBkt()
    {
        return this._lBkt_;
    }

    public void setLBkt(TLBkt node)
    {
        if(this._lBkt_ != null)
        {
            this._lBkt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lBkt_ = node;
    }

    public PDefined getDefined()
    {
        return this._defined_;
    }

    public void setDefined(PDefined node)
    {
        if(this._defined_ != null)
        {
            this._defined_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._defined_ = node;
    }

    public TRBkt getRBkt()
    {
        return this._rBkt_;
    }

    public void setRBkt(TRBkt node)
    {
        if(this._rBkt_ != null)
        {
            this._rBkt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._rBkt_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._chn_)
            + toString(this._lBkt_)
            + toString(this._defined_)
            + toString(this._rBkt_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._chn_ == child)
        {
            this._chn_ = null;
            return;
        }

        if(this._lBkt_ == child)
        {
            this._lBkt_ = null;
            return;
        }

        if(this._defined_ == child)
        {
            this._defined_ = null;
            return;
        }

        if(this._rBkt_ == child)
        {
            this._rBkt_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._chn_ == oldChild)
        {
            setChn((TChn) newChild);
            return;
        }

        if(this._lBkt_ == oldChild)
        {
            setLBkt((TLBkt) newChild);
            return;
        }

        if(this._defined_ == oldChild)
        {
            setDefined((PDefined) newChild);
            return;
        }

        if(this._rBkt_ == oldChild)
        {
            setRBkt((TRBkt) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
