/**
 * generated by Xtext 2.13.0
 */
package org.xtext.unina.xdstmdata.xDstmdata.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.unina.xdstmdata.xDstmdata.XDstmdataPackage;
import org.xtext.unina.xdstmdata.xDstmdata.channel_specifier;
import org.xtext.unina.xdstmdata.xDstmdata.composingtype;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>composingtype</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.unina.xdstmdata.xDstmdata.impl.composingtypeImpl#getTString <em>TString</em>}</li>
 *   <li>{@link org.xtext.unina.xdstmdata.xDstmdata.impl.composingtypeImpl#getTChn <em>TChn</em>}</li>
 *   <li>{@link org.xtext.unina.xdstmdata.xDstmdata.impl.composingtypeImpl#getTID <em>TID</em>}</li>
 * </ul>
 *
 * @generated
 */
public class composingtypeImpl extends MinimalEObjectImpl.Container implements composingtype
{
  /**
   * The default value of the '{@link #getTString() <em>TString</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTString()
   * @generated
   * @ordered
   */
  protected static final String TSTRING_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getTString() <em>TString</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTString()
   * @generated
   * @ordered
   */
  protected String tString = TSTRING_EDEFAULT;

  /**
   * The cached value of the '{@link #getTChn() <em>TChn</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTChn()
   * @generated
   * @ordered
   */
  protected channel_specifier tChn;

  /**
   * The default value of the '{@link #getTID() <em>TID</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTID()
   * @generated
   * @ordered
   */
  protected static final String TID_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getTID() <em>TID</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTID()
   * @generated
   * @ordered
   */
  protected String tID = TID_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected composingtypeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return XDstmdataPackage.Literals.COMPOSINGTYPE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getTString()
  {
    return tString;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setTString(String newTString)
  {
    String oldTString = tString;
    tString = newTString;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, XDstmdataPackage.COMPOSINGTYPE__TSTRING, oldTString, tString));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public channel_specifier getTChn()
  {
    return tChn;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetTChn(channel_specifier newTChn, NotificationChain msgs)
  {
    channel_specifier oldTChn = tChn;
    tChn = newTChn;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, XDstmdataPackage.COMPOSINGTYPE__TCHN, oldTChn, newTChn);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setTChn(channel_specifier newTChn)
  {
    if (newTChn != tChn)
    {
      NotificationChain msgs = null;
      if (tChn != null)
        msgs = ((InternalEObject)tChn).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - XDstmdataPackage.COMPOSINGTYPE__TCHN, null, msgs);
      if (newTChn != null)
        msgs = ((InternalEObject)newTChn).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - XDstmdataPackage.COMPOSINGTYPE__TCHN, null, msgs);
      msgs = basicSetTChn(newTChn, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, XDstmdataPackage.COMPOSINGTYPE__TCHN, newTChn, newTChn));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getTID()
  {
    return tID;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setTID(String newTID)
  {
    String oldTID = tID;
    tID = newTID;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, XDstmdataPackage.COMPOSINGTYPE__TID, oldTID, tID));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case XDstmdataPackage.COMPOSINGTYPE__TCHN:
        return basicSetTChn(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case XDstmdataPackage.COMPOSINGTYPE__TSTRING:
        return getTString();
      case XDstmdataPackage.COMPOSINGTYPE__TCHN:
        return getTChn();
      case XDstmdataPackage.COMPOSINGTYPE__TID:
        return getTID();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case XDstmdataPackage.COMPOSINGTYPE__TSTRING:
        setTString((String)newValue);
        return;
      case XDstmdataPackage.COMPOSINGTYPE__TCHN:
        setTChn((channel_specifier)newValue);
        return;
      case XDstmdataPackage.COMPOSINGTYPE__TID:
        setTID((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case XDstmdataPackage.COMPOSINGTYPE__TSTRING:
        setTString(TSTRING_EDEFAULT);
        return;
      case XDstmdataPackage.COMPOSINGTYPE__TCHN:
        setTChn((channel_specifier)null);
        return;
      case XDstmdataPackage.COMPOSINGTYPE__TID:
        setTID(TID_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case XDstmdataPackage.COMPOSINGTYPE__TSTRING:
        return TSTRING_EDEFAULT == null ? tString != null : !TSTRING_EDEFAULT.equals(tString);
      case XDstmdataPackage.COMPOSINGTYPE__TCHN:
        return tChn != null;
      case XDstmdataPackage.COMPOSINGTYPE__TID:
        return TID_EDEFAULT == null ? tID != null : !TID_EDEFAULT.equals(tID);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (tString: ");
    result.append(tString);
    result.append(", tID: ");
    result.append(tID);
    result.append(')');
    return result.toString();
  }

} //composingtypeImpl
