/**
 * generated by Xtext 2.13.0
 */
package org.xtext.unina.xdstm.xDstm.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.unina.xdstm.xDstm.InitialNode;
import org.xtext.unina.xdstm.xDstm.XDstmPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Initial Node</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class InitialNodeImpl extends EnteringNodeAbsImpl implements InitialNode
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected InitialNodeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return XDstmPackage.Literals.INITIAL_NODE;
  }

} //InitialNodeImpl
