/**
 * generated by Xtext 2.13.0
 */
package org.xtext.unina.xdstmdata.xDstmdata;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>cIntchannel</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.unina.xdstmdata.xDstmdata.cIntchannel#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.unina.xdstmdata.xDstmdata.cIntchannel#getBound <em>Bound</em>}</li>
 *   <li>{@link org.xtext.unina.xdstmdata.xDstmdata.cIntchannel#getTString <em>TString</em>}</li>
 *   <li>{@link org.xtext.unina.xdstmdata.xDstmdata.cIntchannel#getTChn <em>TChn</em>}</li>
 *   <li>{@link org.xtext.unina.xdstmdata.xDstmdata.cIntchannel#getTID <em>TID</em>}</li>
 * </ul>
 *
 * @see org.xtext.unina.xdstmdata.xDstmdata.XDstmdataPackage#getcIntchannel()
 * @model
 * @generated
 */
public interface cIntchannel extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.unina.xdstmdata.xDstmdata.XDstmdataPackage#getcIntchannel_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.unina.xdstmdata.xDstmdata.cIntchannel#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Bound</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Bound</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Bound</em>' attribute.
   * @see #setBound(int)
   * @see org.xtext.unina.xdstmdata.xDstmdata.XDstmdataPackage#getcIntchannel_Bound()
   * @model
   * @generated
   */
  int getBound();

  /**
   * Sets the value of the '{@link org.xtext.unina.xdstmdata.xDstmdata.cIntchannel#getBound <em>Bound</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Bound</em>' attribute.
   * @see #getBound()
   * @generated
   */
  void setBound(int value);

  /**
   * Returns the value of the '<em><b>TString</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>TString</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>TString</em>' attribute.
   * @see #setTString(String)
   * @see org.xtext.unina.xdstmdata.xDstmdata.XDstmdataPackage#getcIntchannel_TString()
   * @model
   * @generated
   */
  String getTString();

  /**
   * Sets the value of the '{@link org.xtext.unina.xdstmdata.xDstmdata.cIntchannel#getTString <em>TString</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>TString</em>' attribute.
   * @see #getTString()
   * @generated
   */
  void setTString(String value);

  /**
   * Returns the value of the '<em><b>TChn</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>TChn</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>TChn</em>' containment reference.
   * @see #setTChn(channel_specifier)
   * @see org.xtext.unina.xdstmdata.xDstmdata.XDstmdataPackage#getcIntchannel_TChn()
   * @model containment="true"
   * @generated
   */
  channel_specifier getTChn();

  /**
   * Sets the value of the '{@link org.xtext.unina.xdstmdata.xDstmdata.cIntchannel#getTChn <em>TChn</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>TChn</em>' containment reference.
   * @see #getTChn()
   * @generated
   */
  void setTChn(channel_specifier value);

  /**
   * Returns the value of the '<em><b>TID</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>TID</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>TID</em>' attribute.
   * @see #setTID(String)
   * @see org.xtext.unina.xdstmdata.xDstmdata.XDstmdataPackage#getcIntchannel_TID()
   * @model
   * @generated
   */
  String getTID();

  /**
   * Sets the value of the '{@link org.xtext.unina.xdstmdata.xDstmdata.cIntchannel#getTID <em>TID</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>TID</em>' attribute.
   * @see #getTID()
   * @generated
   */
  void setTID(String value);

} // cIntchannel
