/**
 * generated by Xtext 2.13.0
 */
package org.xtext.unina.xdstmdata.xDstmdata;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.unina.xdstmdata.xDstmdata.XDstmdataFactory
 * @model kind="package"
 * @generated
 */
public interface XDstmdataPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "xDstmdata";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/unina/xdstm/XDstmdata";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "xDstmdata";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  XDstmdataPackage eINSTANCE = org.xtext.unina.xdstmdata.xDstmdata.impl.XDstmdataPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.unina.xdstmdata.xDstmdata.impl.tTypesImpl <em>tTypes</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.unina.xdstmdata.xDstmdata.impl.tTypesImpl
   * @see org.xtext.unina.xdstmdata.xDstmdata.impl.XDstmdataPackageImpl#gettTypes()
   * @generated
   */
  int TTYPES = 0;

  /**
   * The feature id for the '<em><b>TEnum</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TTYPES__TENUM = 0;

  /**
   * The feature id for the '<em><b>TCompound</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TTYPES__TCOMPOUND = 1;

  /**
   * The feature id for the '<em><b>TMultitype</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TTYPES__TMULTITYPE = 2;

  /**
   * The feature id for the '<em><b>CIntchannel</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TTYPES__CINTCHANNEL = 3;

  /**
   * The feature id for the '<em><b>CExtchannel</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TTYPES__CEXTCHANNEL = 4;

  /**
   * The feature id for the '<em><b>VVariable</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TTYPES__VVARIABLE = 5;

  /**
   * The number of structural features of the '<em>tTypes</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TTYPES_FEATURE_COUNT = 6;

  /**
   * The meta object id for the '{@link org.xtext.unina.xdstmdata.xDstmdata.impl.tEnumImpl <em>tEnum</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.unina.xdstmdata.xDstmdata.impl.tEnumImpl
   * @see org.xtext.unina.xdstmdata.xDstmdata.impl.XDstmdataPackageImpl#gettEnum()
   * @generated
   */
  int TENUM = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TENUM__NAME = 0;

  /**
   * The feature id for the '<em><b>Literals</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TENUM__LITERALS = 1;

  /**
   * The number of structural features of the '<em>tEnum</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TENUM_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.unina.xdstmdata.xDstmdata.impl.tCompoundImpl <em>tCompound</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.unina.xdstmdata.xDstmdata.impl.tCompoundImpl
   * @see org.xtext.unina.xdstmdata.xDstmdata.impl.XDstmdataPackageImpl#gettCompound()
   * @generated
   */
  int TCOMPOUND = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TCOMPOUND__NAME = 0;

  /**
   * The feature id for the '<em><b>Subtypes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TCOMPOUND__SUBTYPES = 1;

  /**
   * The number of structural features of the '<em>tCompound</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TCOMPOUND_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.unina.xdstmdata.xDstmdata.impl.subtypeImpl <em>subtype</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.unina.xdstmdata.xDstmdata.impl.subtypeImpl
   * @see org.xtext.unina.xdstmdata.xDstmdata.impl.XDstmdataPackageImpl#getsubtype()
   * @generated
   */
  int SUBTYPE = 3;

  /**
   * The feature id for the '<em><b>TString</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUBTYPE__TSTRING = 0;

  /**
   * The feature id for the '<em><b>TChn</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUBTYPE__TCHN = 1;

  /**
   * The feature id for the '<em><b>TID</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUBTYPE__TID = 2;

  /**
   * The number of structural features of the '<em>subtype</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUBTYPE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.unina.xdstmdata.xDstmdata.impl.channel_specifierImpl <em>channel specifier</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.unina.xdstmdata.xDstmdata.impl.channel_specifierImpl
   * @see org.xtext.unina.xdstmdata.xDstmdata.impl.XDstmdataPackageImpl#getchannel_specifier()
   * @generated
   */
  int CHANNEL_SPECIFIER = 4;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHANNEL_SPECIFIER__TYPE = 0;

  /**
   * The number of structural features of the '<em>channel specifier</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHANNEL_SPECIFIER_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.unina.xdstmdata.xDstmdata.impl.tMultitypeImpl <em>tMultitype</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.unina.xdstmdata.xDstmdata.impl.tMultitypeImpl
   * @see org.xtext.unina.xdstmdata.xDstmdata.impl.XDstmdataPackageImpl#gettMultitype()
   * @generated
   */
  int TMULTITYPE = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TMULTITYPE__NAME = 0;

  /**
   * The feature id for the '<em><b>Composingtypes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TMULTITYPE__COMPOSINGTYPES = 1;

  /**
   * The number of structural features of the '<em>tMultitype</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TMULTITYPE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.unina.xdstmdata.xDstmdata.impl.composingtypeImpl <em>composingtype</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.unina.xdstmdata.xDstmdata.impl.composingtypeImpl
   * @see org.xtext.unina.xdstmdata.xDstmdata.impl.XDstmdataPackageImpl#getcomposingtype()
   * @generated
   */
  int COMPOSINGTYPE = 6;

  /**
   * The feature id for the '<em><b>TString</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPOSINGTYPE__TSTRING = 0;

  /**
   * The feature id for the '<em><b>TChn</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPOSINGTYPE__TCHN = 1;

  /**
   * The feature id for the '<em><b>TID</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPOSINGTYPE__TID = 2;

  /**
   * The number of structural features of the '<em>composingtype</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPOSINGTYPE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.unina.xdstmdata.xDstmdata.impl.cIntchannelImpl <em>cIntchannel</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.unina.xdstmdata.xDstmdata.impl.cIntchannelImpl
   * @see org.xtext.unina.xdstmdata.xDstmdata.impl.XDstmdataPackageImpl#getcIntchannel()
   * @generated
   */
  int CINTCHANNEL = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CINTCHANNEL__NAME = 0;

  /**
   * The feature id for the '<em><b>Bound</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CINTCHANNEL__BOUND = 1;

  /**
   * The feature id for the '<em><b>TString</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CINTCHANNEL__TSTRING = 2;

  /**
   * The feature id for the '<em><b>TChn</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CINTCHANNEL__TCHN = 3;

  /**
   * The feature id for the '<em><b>TID</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CINTCHANNEL__TID = 4;

  /**
   * The number of structural features of the '<em>cIntchannel</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CINTCHANNEL_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link org.xtext.unina.xdstmdata.xDstmdata.impl.cExtchannelImpl <em>cExtchannel</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.unina.xdstmdata.xDstmdata.impl.cExtchannelImpl
   * @see org.xtext.unina.xdstmdata.xDstmdata.impl.XDstmdataPackageImpl#getcExtchannel()
   * @generated
   */
  int CEXTCHANNEL = 8;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CEXTCHANNEL__NAME = 0;

  /**
   * The feature id for the '<em><b>TString</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CEXTCHANNEL__TSTRING = 1;

  /**
   * The feature id for the '<em><b>TChn</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CEXTCHANNEL__TCHN = 2;

  /**
   * The feature id for the '<em><b>TID</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CEXTCHANNEL__TID = 3;

  /**
   * The number of structural features of the '<em>cExtchannel</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CEXTCHANNEL_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.unina.xdstmdata.xDstmdata.impl.vVariableImpl <em>vVariable</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.unina.xdstmdata.xDstmdata.impl.vVariableImpl
   * @see org.xtext.unina.xdstmdata.xDstmdata.impl.XDstmdataPackageImpl#getvVariable()
   * @generated
   */
  int VVARIABLE = 9;

  /**
   * The feature id for the '<em><b>TString</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VVARIABLE__TSTRING = 0;

  /**
   * The feature id for the '<em><b>TChn</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VVARIABLE__TCHN = 1;

  /**
   * The feature id for the '<em><b>TID</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VVARIABLE__TID = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VVARIABLE__NAME = 3;

  /**
   * The number of structural features of the '<em>vVariable</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VVARIABLE_FEATURE_COUNT = 4;


  /**
   * Returns the meta object for class '{@link org.xtext.unina.xdstmdata.xDstmdata.tTypes <em>tTypes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>tTypes</em>'.
   * @see org.xtext.unina.xdstmdata.xDstmdata.tTypes
   * @generated
   */
  EClass gettTypes();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.unina.xdstmdata.xDstmdata.tTypes#getTEnum <em>TEnum</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>TEnum</em>'.
   * @see org.xtext.unina.xdstmdata.xDstmdata.tTypes#getTEnum()
   * @see #gettTypes()
   * @generated
   */
  EReference gettTypes_TEnum();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.unina.xdstmdata.xDstmdata.tTypes#getTCompound <em>TCompound</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>TCompound</em>'.
   * @see org.xtext.unina.xdstmdata.xDstmdata.tTypes#getTCompound()
   * @see #gettTypes()
   * @generated
   */
  EReference gettTypes_TCompound();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.unina.xdstmdata.xDstmdata.tTypes#getTMultitype <em>TMultitype</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>TMultitype</em>'.
   * @see org.xtext.unina.xdstmdata.xDstmdata.tTypes#getTMultitype()
   * @see #gettTypes()
   * @generated
   */
  EReference gettTypes_TMultitype();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.unina.xdstmdata.xDstmdata.tTypes#getCIntchannel <em>CIntchannel</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>CIntchannel</em>'.
   * @see org.xtext.unina.xdstmdata.xDstmdata.tTypes#getCIntchannel()
   * @see #gettTypes()
   * @generated
   */
  EReference gettTypes_CIntchannel();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.unina.xdstmdata.xDstmdata.tTypes#getCExtchannel <em>CExtchannel</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>CExtchannel</em>'.
   * @see org.xtext.unina.xdstmdata.xDstmdata.tTypes#getCExtchannel()
   * @see #gettTypes()
   * @generated
   */
  EReference gettTypes_CExtchannel();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.unina.xdstmdata.xDstmdata.tTypes#getVVariable <em>VVariable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>VVariable</em>'.
   * @see org.xtext.unina.xdstmdata.xDstmdata.tTypes#getVVariable()
   * @see #gettTypes()
   * @generated
   */
  EReference gettTypes_VVariable();

  /**
   * Returns the meta object for class '{@link org.xtext.unina.xdstmdata.xDstmdata.tEnum <em>tEnum</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>tEnum</em>'.
   * @see org.xtext.unina.xdstmdata.xDstmdata.tEnum
   * @generated
   */
  EClass gettEnum();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.unina.xdstmdata.xDstmdata.tEnum#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.unina.xdstmdata.xDstmdata.tEnum#getName()
   * @see #gettEnum()
   * @generated
   */
  EAttribute gettEnum_Name();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.unina.xdstmdata.xDstmdata.tEnum#getLiterals <em>Literals</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Literals</em>'.
   * @see org.xtext.unina.xdstmdata.xDstmdata.tEnum#getLiterals()
   * @see #gettEnum()
   * @generated
   */
  EAttribute gettEnum_Literals();

  /**
   * Returns the meta object for class '{@link org.xtext.unina.xdstmdata.xDstmdata.tCompound <em>tCompound</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>tCompound</em>'.
   * @see org.xtext.unina.xdstmdata.xDstmdata.tCompound
   * @generated
   */
  EClass gettCompound();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.unina.xdstmdata.xDstmdata.tCompound#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.unina.xdstmdata.xDstmdata.tCompound#getName()
   * @see #gettCompound()
   * @generated
   */
  EAttribute gettCompound_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.unina.xdstmdata.xDstmdata.tCompound#getSubtypes <em>Subtypes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Subtypes</em>'.
   * @see org.xtext.unina.xdstmdata.xDstmdata.tCompound#getSubtypes()
   * @see #gettCompound()
   * @generated
   */
  EReference gettCompound_Subtypes();

  /**
   * Returns the meta object for class '{@link org.xtext.unina.xdstmdata.xDstmdata.subtype <em>subtype</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>subtype</em>'.
   * @see org.xtext.unina.xdstmdata.xDstmdata.subtype
   * @generated
   */
  EClass getsubtype();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.unina.xdstmdata.xDstmdata.subtype#getTString <em>TString</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>TString</em>'.
   * @see org.xtext.unina.xdstmdata.xDstmdata.subtype#getTString()
   * @see #getsubtype()
   * @generated
   */
  EAttribute getsubtype_TString();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.unina.xdstmdata.xDstmdata.subtype#getTChn <em>TChn</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>TChn</em>'.
   * @see org.xtext.unina.xdstmdata.xDstmdata.subtype#getTChn()
   * @see #getsubtype()
   * @generated
   */
  EReference getsubtype_TChn();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.unina.xdstmdata.xDstmdata.subtype#getTID <em>TID</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>TID</em>'.
   * @see org.xtext.unina.xdstmdata.xDstmdata.subtype#getTID()
   * @see #getsubtype()
   * @generated
   */
  EAttribute getsubtype_TID();

  /**
   * Returns the meta object for class '{@link org.xtext.unina.xdstmdata.xDstmdata.channel_specifier <em>channel specifier</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>channel specifier</em>'.
   * @see org.xtext.unina.xdstmdata.xDstmdata.channel_specifier
   * @generated
   */
  EClass getchannel_specifier();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.unina.xdstmdata.xDstmdata.channel_specifier#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see org.xtext.unina.xdstmdata.xDstmdata.channel_specifier#getType()
   * @see #getchannel_specifier()
   * @generated
   */
  EAttribute getchannel_specifier_Type();

  /**
   * Returns the meta object for class '{@link org.xtext.unina.xdstmdata.xDstmdata.tMultitype <em>tMultitype</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>tMultitype</em>'.
   * @see org.xtext.unina.xdstmdata.xDstmdata.tMultitype
   * @generated
   */
  EClass gettMultitype();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.unina.xdstmdata.xDstmdata.tMultitype#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.unina.xdstmdata.xDstmdata.tMultitype#getName()
   * @see #gettMultitype()
   * @generated
   */
  EAttribute gettMultitype_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.unina.xdstmdata.xDstmdata.tMultitype#getComposingtypes <em>Composingtypes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Composingtypes</em>'.
   * @see org.xtext.unina.xdstmdata.xDstmdata.tMultitype#getComposingtypes()
   * @see #gettMultitype()
   * @generated
   */
  EReference gettMultitype_Composingtypes();

  /**
   * Returns the meta object for class '{@link org.xtext.unina.xdstmdata.xDstmdata.composingtype <em>composingtype</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>composingtype</em>'.
   * @see org.xtext.unina.xdstmdata.xDstmdata.composingtype
   * @generated
   */
  EClass getcomposingtype();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.unina.xdstmdata.xDstmdata.composingtype#getTString <em>TString</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>TString</em>'.
   * @see org.xtext.unina.xdstmdata.xDstmdata.composingtype#getTString()
   * @see #getcomposingtype()
   * @generated
   */
  EAttribute getcomposingtype_TString();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.unina.xdstmdata.xDstmdata.composingtype#getTChn <em>TChn</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>TChn</em>'.
   * @see org.xtext.unina.xdstmdata.xDstmdata.composingtype#getTChn()
   * @see #getcomposingtype()
   * @generated
   */
  EReference getcomposingtype_TChn();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.unina.xdstmdata.xDstmdata.composingtype#getTID <em>TID</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>TID</em>'.
   * @see org.xtext.unina.xdstmdata.xDstmdata.composingtype#getTID()
   * @see #getcomposingtype()
   * @generated
   */
  EAttribute getcomposingtype_TID();

  /**
   * Returns the meta object for class '{@link org.xtext.unina.xdstmdata.xDstmdata.cIntchannel <em>cIntchannel</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>cIntchannel</em>'.
   * @see org.xtext.unina.xdstmdata.xDstmdata.cIntchannel
   * @generated
   */
  EClass getcIntchannel();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.unina.xdstmdata.xDstmdata.cIntchannel#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.unina.xdstmdata.xDstmdata.cIntchannel#getName()
   * @see #getcIntchannel()
   * @generated
   */
  EAttribute getcIntchannel_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.unina.xdstmdata.xDstmdata.cIntchannel#getBound <em>Bound</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Bound</em>'.
   * @see org.xtext.unina.xdstmdata.xDstmdata.cIntchannel#getBound()
   * @see #getcIntchannel()
   * @generated
   */
  EAttribute getcIntchannel_Bound();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.unina.xdstmdata.xDstmdata.cIntchannel#getTString <em>TString</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>TString</em>'.
   * @see org.xtext.unina.xdstmdata.xDstmdata.cIntchannel#getTString()
   * @see #getcIntchannel()
   * @generated
   */
  EAttribute getcIntchannel_TString();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.unina.xdstmdata.xDstmdata.cIntchannel#getTChn <em>TChn</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>TChn</em>'.
   * @see org.xtext.unina.xdstmdata.xDstmdata.cIntchannel#getTChn()
   * @see #getcIntchannel()
   * @generated
   */
  EReference getcIntchannel_TChn();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.unina.xdstmdata.xDstmdata.cIntchannel#getTID <em>TID</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>TID</em>'.
   * @see org.xtext.unina.xdstmdata.xDstmdata.cIntchannel#getTID()
   * @see #getcIntchannel()
   * @generated
   */
  EAttribute getcIntchannel_TID();

  /**
   * Returns the meta object for class '{@link org.xtext.unina.xdstmdata.xDstmdata.cExtchannel <em>cExtchannel</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>cExtchannel</em>'.
   * @see org.xtext.unina.xdstmdata.xDstmdata.cExtchannel
   * @generated
   */
  EClass getcExtchannel();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.unina.xdstmdata.xDstmdata.cExtchannel#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.unina.xdstmdata.xDstmdata.cExtchannel#getName()
   * @see #getcExtchannel()
   * @generated
   */
  EAttribute getcExtchannel_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.unina.xdstmdata.xDstmdata.cExtchannel#getTString <em>TString</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>TString</em>'.
   * @see org.xtext.unina.xdstmdata.xDstmdata.cExtchannel#getTString()
   * @see #getcExtchannel()
   * @generated
   */
  EAttribute getcExtchannel_TString();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.unina.xdstmdata.xDstmdata.cExtchannel#getTChn <em>TChn</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>TChn</em>'.
   * @see org.xtext.unina.xdstmdata.xDstmdata.cExtchannel#getTChn()
   * @see #getcExtchannel()
   * @generated
   */
  EReference getcExtchannel_TChn();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.unina.xdstmdata.xDstmdata.cExtchannel#getTID <em>TID</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>TID</em>'.
   * @see org.xtext.unina.xdstmdata.xDstmdata.cExtchannel#getTID()
   * @see #getcExtchannel()
   * @generated
   */
  EAttribute getcExtchannel_TID();

  /**
   * Returns the meta object for class '{@link org.xtext.unina.xdstmdata.xDstmdata.vVariable <em>vVariable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>vVariable</em>'.
   * @see org.xtext.unina.xdstmdata.xDstmdata.vVariable
   * @generated
   */
  EClass getvVariable();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.unina.xdstmdata.xDstmdata.vVariable#getTString <em>TString</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>TString</em>'.
   * @see org.xtext.unina.xdstmdata.xDstmdata.vVariable#getTString()
   * @see #getvVariable()
   * @generated
   */
  EAttribute getvVariable_TString();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.unina.xdstmdata.xDstmdata.vVariable#getTChn <em>TChn</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>TChn</em>'.
   * @see org.xtext.unina.xdstmdata.xDstmdata.vVariable#getTChn()
   * @see #getvVariable()
   * @generated
   */
  EReference getvVariable_TChn();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.unina.xdstmdata.xDstmdata.vVariable#getTID <em>TID</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>TID</em>'.
   * @see org.xtext.unina.xdstmdata.xDstmdata.vVariable#getTID()
   * @see #getvVariable()
   * @generated
   */
  EAttribute getvVariable_TID();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.unina.xdstmdata.xDstmdata.vVariable#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.unina.xdstmdata.xDstmdata.vVariable#getName()
   * @see #getvVariable()
   * @generated
   */
  EAttribute getvVariable_Name();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  XDstmdataFactory getXDstmdataFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.unina.xdstmdata.xDstmdata.impl.tTypesImpl <em>tTypes</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.unina.xdstmdata.xDstmdata.impl.tTypesImpl
     * @see org.xtext.unina.xdstmdata.xDstmdata.impl.XDstmdataPackageImpl#gettTypes()
     * @generated
     */
    EClass TTYPES = eINSTANCE.gettTypes();

    /**
     * The meta object literal for the '<em><b>TEnum</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TTYPES__TENUM = eINSTANCE.gettTypes_TEnum();

    /**
     * The meta object literal for the '<em><b>TCompound</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TTYPES__TCOMPOUND = eINSTANCE.gettTypes_TCompound();

    /**
     * The meta object literal for the '<em><b>TMultitype</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TTYPES__TMULTITYPE = eINSTANCE.gettTypes_TMultitype();

    /**
     * The meta object literal for the '<em><b>CIntchannel</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TTYPES__CINTCHANNEL = eINSTANCE.gettTypes_CIntchannel();

    /**
     * The meta object literal for the '<em><b>CExtchannel</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TTYPES__CEXTCHANNEL = eINSTANCE.gettTypes_CExtchannel();

    /**
     * The meta object literal for the '<em><b>VVariable</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TTYPES__VVARIABLE = eINSTANCE.gettTypes_VVariable();

    /**
     * The meta object literal for the '{@link org.xtext.unina.xdstmdata.xDstmdata.impl.tEnumImpl <em>tEnum</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.unina.xdstmdata.xDstmdata.impl.tEnumImpl
     * @see org.xtext.unina.xdstmdata.xDstmdata.impl.XDstmdataPackageImpl#gettEnum()
     * @generated
     */
    EClass TENUM = eINSTANCE.gettEnum();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TENUM__NAME = eINSTANCE.gettEnum_Name();

    /**
     * The meta object literal for the '<em><b>Literals</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TENUM__LITERALS = eINSTANCE.gettEnum_Literals();

    /**
     * The meta object literal for the '{@link org.xtext.unina.xdstmdata.xDstmdata.impl.tCompoundImpl <em>tCompound</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.unina.xdstmdata.xDstmdata.impl.tCompoundImpl
     * @see org.xtext.unina.xdstmdata.xDstmdata.impl.XDstmdataPackageImpl#gettCompound()
     * @generated
     */
    EClass TCOMPOUND = eINSTANCE.gettCompound();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TCOMPOUND__NAME = eINSTANCE.gettCompound_Name();

    /**
     * The meta object literal for the '<em><b>Subtypes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TCOMPOUND__SUBTYPES = eINSTANCE.gettCompound_Subtypes();

    /**
     * The meta object literal for the '{@link org.xtext.unina.xdstmdata.xDstmdata.impl.subtypeImpl <em>subtype</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.unina.xdstmdata.xDstmdata.impl.subtypeImpl
     * @see org.xtext.unina.xdstmdata.xDstmdata.impl.XDstmdataPackageImpl#getsubtype()
     * @generated
     */
    EClass SUBTYPE = eINSTANCE.getsubtype();

    /**
     * The meta object literal for the '<em><b>TString</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SUBTYPE__TSTRING = eINSTANCE.getsubtype_TString();

    /**
     * The meta object literal for the '<em><b>TChn</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SUBTYPE__TCHN = eINSTANCE.getsubtype_TChn();

    /**
     * The meta object literal for the '<em><b>TID</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SUBTYPE__TID = eINSTANCE.getsubtype_TID();

    /**
     * The meta object literal for the '{@link org.xtext.unina.xdstmdata.xDstmdata.impl.channel_specifierImpl <em>channel specifier</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.unina.xdstmdata.xDstmdata.impl.channel_specifierImpl
     * @see org.xtext.unina.xdstmdata.xDstmdata.impl.XDstmdataPackageImpl#getchannel_specifier()
     * @generated
     */
    EClass CHANNEL_SPECIFIER = eINSTANCE.getchannel_specifier();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CHANNEL_SPECIFIER__TYPE = eINSTANCE.getchannel_specifier_Type();

    /**
     * The meta object literal for the '{@link org.xtext.unina.xdstmdata.xDstmdata.impl.tMultitypeImpl <em>tMultitype</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.unina.xdstmdata.xDstmdata.impl.tMultitypeImpl
     * @see org.xtext.unina.xdstmdata.xDstmdata.impl.XDstmdataPackageImpl#gettMultitype()
     * @generated
     */
    EClass TMULTITYPE = eINSTANCE.gettMultitype();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TMULTITYPE__NAME = eINSTANCE.gettMultitype_Name();

    /**
     * The meta object literal for the '<em><b>Composingtypes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TMULTITYPE__COMPOSINGTYPES = eINSTANCE.gettMultitype_Composingtypes();

    /**
     * The meta object literal for the '{@link org.xtext.unina.xdstmdata.xDstmdata.impl.composingtypeImpl <em>composingtype</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.unina.xdstmdata.xDstmdata.impl.composingtypeImpl
     * @see org.xtext.unina.xdstmdata.xDstmdata.impl.XDstmdataPackageImpl#getcomposingtype()
     * @generated
     */
    EClass COMPOSINGTYPE = eINSTANCE.getcomposingtype();

    /**
     * The meta object literal for the '<em><b>TString</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMPOSINGTYPE__TSTRING = eINSTANCE.getcomposingtype_TString();

    /**
     * The meta object literal for the '<em><b>TChn</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPOSINGTYPE__TCHN = eINSTANCE.getcomposingtype_TChn();

    /**
     * The meta object literal for the '<em><b>TID</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMPOSINGTYPE__TID = eINSTANCE.getcomposingtype_TID();

    /**
     * The meta object literal for the '{@link org.xtext.unina.xdstmdata.xDstmdata.impl.cIntchannelImpl <em>cIntchannel</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.unina.xdstmdata.xDstmdata.impl.cIntchannelImpl
     * @see org.xtext.unina.xdstmdata.xDstmdata.impl.XDstmdataPackageImpl#getcIntchannel()
     * @generated
     */
    EClass CINTCHANNEL = eINSTANCE.getcIntchannel();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CINTCHANNEL__NAME = eINSTANCE.getcIntchannel_Name();

    /**
     * The meta object literal for the '<em><b>Bound</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CINTCHANNEL__BOUND = eINSTANCE.getcIntchannel_Bound();

    /**
     * The meta object literal for the '<em><b>TString</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CINTCHANNEL__TSTRING = eINSTANCE.getcIntchannel_TString();

    /**
     * The meta object literal for the '<em><b>TChn</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CINTCHANNEL__TCHN = eINSTANCE.getcIntchannel_TChn();

    /**
     * The meta object literal for the '<em><b>TID</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CINTCHANNEL__TID = eINSTANCE.getcIntchannel_TID();

    /**
     * The meta object literal for the '{@link org.xtext.unina.xdstmdata.xDstmdata.impl.cExtchannelImpl <em>cExtchannel</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.unina.xdstmdata.xDstmdata.impl.cExtchannelImpl
     * @see org.xtext.unina.xdstmdata.xDstmdata.impl.XDstmdataPackageImpl#getcExtchannel()
     * @generated
     */
    EClass CEXTCHANNEL = eINSTANCE.getcExtchannel();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CEXTCHANNEL__NAME = eINSTANCE.getcExtchannel_Name();

    /**
     * The meta object literal for the '<em><b>TString</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CEXTCHANNEL__TSTRING = eINSTANCE.getcExtchannel_TString();

    /**
     * The meta object literal for the '<em><b>TChn</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CEXTCHANNEL__TCHN = eINSTANCE.getcExtchannel_TChn();

    /**
     * The meta object literal for the '<em><b>TID</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CEXTCHANNEL__TID = eINSTANCE.getcExtchannel_TID();

    /**
     * The meta object literal for the '{@link org.xtext.unina.xdstmdata.xDstmdata.impl.vVariableImpl <em>vVariable</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.unina.xdstmdata.xDstmdata.impl.vVariableImpl
     * @see org.xtext.unina.xdstmdata.xDstmdata.impl.XDstmdataPackageImpl#getvVariable()
     * @generated
     */
    EClass VVARIABLE = eINSTANCE.getvVariable();

    /**
     * The meta object literal for the '<em><b>TString</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VVARIABLE__TSTRING = eINSTANCE.getvVariable_TString();

    /**
     * The meta object literal for the '<em><b>TChn</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VVARIABLE__TCHN = eINSTANCE.getvVariable_TChn();

    /**
     * The meta object literal for the '<em><b>TID</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VVARIABLE__TID = eINSTANCE.getvVariable_TID();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VVARIABLE__NAME = eINSTANCE.getvVariable_Name();

  }

} //XDstmdataPackage
