/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.prgmdl.dstmverifier.transition.action.node;

import org.prgmdl.dstmverifier.transition.action.analysis.*;

@SuppressWarnings("nls")
public final class AComplexExprlist extends PExprlist
{
    private PExpr _expr_;
    private TComma _comma_;
    private PExprlist _exprlist_;

    public AComplexExprlist()
    {
        // Constructor
    }

    public AComplexExprlist(
        @SuppressWarnings("hiding") PExpr _expr_,
        @SuppressWarnings("hiding") TComma _comma_,
        @SuppressWarnings("hiding") PExprlist _exprlist_)
    {
        // Constructor
        setExpr(_expr_);

        setComma(_comma_);

        setExprlist(_exprlist_);

    }

    @Override
    public Object clone()
    {
        return new AComplexExprlist(
            cloneNode(this._expr_),
            cloneNode(this._comma_),
            cloneNode(this._exprlist_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAComplexExprlist(this);
    }

    public PExpr getExpr()
    {
        return this._expr_;
    }

    public void setExpr(PExpr node)
    {
        if(this._expr_ != null)
        {
            this._expr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expr_ = node;
    }

    public TComma getComma()
    {
        return this._comma_;
    }

    public void setComma(TComma node)
    {
        if(this._comma_ != null)
        {
            this._comma_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comma_ = node;
    }

    public PExprlist getExprlist()
    {
        return this._exprlist_;
    }

    public void setExprlist(PExprlist node)
    {
        if(this._exprlist_ != null)
        {
            this._exprlist_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exprlist_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expr_)
            + toString(this._comma_)
            + toString(this._exprlist_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expr_ == child)
        {
            this._expr_ = null;
            return;
        }

        if(this._comma_ == child)
        {
            this._comma_ = null;
            return;
        }

        if(this._exprlist_ == child)
        {
            this._exprlist_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expr_ == oldChild)
        {
            setExpr((PExpr) newChild);
            return;
        }

        if(this._comma_ == oldChild)
        {
            setComma((TComma) newChild);
            return;
        }

        if(this._exprlist_ == oldChild)
        {
            setExprlist((PExprlist) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
