/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.prgmdl.dstmverifier.transition.condition.node;

import org.prgmdl.dstmverifier.transition.condition.analysis.*;

@SuppressWarnings("nls")
public final class AFullcondSize extends PSize
{
    private TFull _full_;

    public AFullcondSize()
    {
        // Constructor
    }

    public AFullcondSize(
        @SuppressWarnings("hiding") TFull _full_)
    {
        // Constructor
        setFull(_full_);

    }

    @Override
    public Object clone()
    {
        return new AFullcondSize(
            cloneNode(this._full_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFullcondSize(this);
    }

    public TFull getFull()
    {
        return this._full_;
    }

    public void setFull(TFull node)
    {
        if(this._full_ != null)
        {
            this._full_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._full_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._full_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._full_ == child)
        {
            this._full_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._full_ == oldChild)
        {
            setFull((TFull) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
