/**
 * generated by Xtext 2.13.0
 */
package org.xtext.unina.xdstm.xDstm;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>DSTM</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.unina.xdstm.xDstm.DSTM#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.unina.xdstm.xDstm.DSTM#getMachines <em>Machines</em>}</li>
 *   <li>{@link org.xtext.unina.xdstm.xDstm.DSTM#getMain <em>Main</em>}</li>
 * </ul>
 *
 * @see org.xtext.unina.xdstm.xDstm.XDstmPackage#getDSTM()
 * @model
 * @generated
 */
public interface DSTM extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.unina.xdstm.xDstm.XDstmPackage#getDSTM_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.unina.xdstm.xDstm.DSTM#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Machines</b></em>' reference list.
   * The list contents are of type {@link org.xtext.unina.xdstm.xDstm.Machine}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Machines</em>' reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Machines</em>' reference list.
   * @see org.xtext.unina.xdstm.xDstm.XDstmPackage#getDSTM_Machines()
   * @model
   * @generated
   */
  EList<Machine> getMachines();

  /**
   * Returns the value of the '<em><b>Main</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Main</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Main</em>' reference.
   * @see #setMain(Machine)
   * @see org.xtext.unina.xdstm.xDstm.XDstmPackage#getDSTM_Main()
   * @model
   * @generated
   */
  Machine getMain();

  /**
   * Sets the value of the '{@link org.xtext.unina.xdstm.xDstm.DSTM#getMain <em>Main</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Main</em>' reference.
   * @see #getMain()
   * @generated
   */
  void setMain(Machine value);

} // DSTM
