/**
 * generated by Xtext 2.13.0
 */
package org.xtext.unina.xdstm.xDstm;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.unina.xdstm.xDstm.Model#getInclude <em>Include</em>}</li>
 *   <li>{@link org.xtext.unina.xdstm.xDstm.Model#getMachines <em>Machines</em>}</li>
 *   <li>{@link org.xtext.unina.xdstm.xDstm.Model#getDstm <em>Dstm</em>}</li>
 * </ul>
 *
 * @see org.xtext.unina.xdstm.xDstm.XDstmPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Include</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Include</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Include</em>' containment reference.
   * @see #setInclude(include)
   * @see org.xtext.unina.xdstm.xDstm.XDstmPackage#getModel_Include()
   * @model containment="true"
   * @generated
   */
  include getInclude();

  /**
   * Sets the value of the '{@link org.xtext.unina.xdstm.xDstm.Model#getInclude <em>Include</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Include</em>' containment reference.
   * @see #getInclude()
   * @generated
   */
  void setInclude(include value);

  /**
   * Returns the value of the '<em><b>Machines</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.unina.xdstm.xDstm.Machine}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Machines</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Machines</em>' containment reference list.
   * @see org.xtext.unina.xdstm.xDstm.XDstmPackage#getModel_Machines()
   * @model containment="true"
   * @generated
   */
  EList<Machine> getMachines();

  /**
   * Returns the value of the '<em><b>Dstm</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.unina.xdstm.xDstm.DSTM}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Dstm</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dstm</em>' containment reference list.
   * @see org.xtext.unina.xdstm.xDstm.XDstmPackage#getModel_Dstm()
   * @model containment="true"
   * @generated
   */
  EList<DSTM> getDstm();

} // Model
