/**
 * generated by Xtext 2.13.0
 */
package org.xtext.unina.xdstm.xDstm;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>requirements</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.unina.xdstm.xDstm.requirements#getRequirements <em>Requirements</em>}</li>
 * </ul>
 *
 * @see org.xtext.unina.xdstm.xDstm.XDstmPackage#getrequirements()
 * @model
 * @generated
 */
public interface requirements extends EObject
{
  /**
   * Returns the value of the '<em><b>Requirements</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Requirements</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Requirements</em>' attribute list.
   * @see org.xtext.unina.xdstm.xDstm.XDstmPackage#getrequirements_Requirements()
   * @model unique="false"
   * @generated
   */
  EList<String> getRequirements();

} // requirements
