/**
 * generated by Xtext 2.13.0
 */
package org.xtext.unina.xdstm.xDstm;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Transition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.unina.xdstm.xDstm.Transition#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.unina.xdstm.xDstm.Transition#getRequirements <em>Requirements</em>}</li>
 *   <li>{@link org.xtext.unina.xdstm.xDstm.Transition#getSource <em>Source</em>}</li>
 *   <li>{@link org.xtext.unina.xdstm.xDstm.Transition#getExiting_node <em>Exiting node</em>}</li>
 *   <li>{@link org.xtext.unina.xdstm.xDstm.Transition#getDestination <em>Destination</em>}</li>
 *   <li>{@link org.xtext.unina.xdstm.xDstm.Transition#getEntering_node <em>Entering node</em>}</li>
 *   <li>{@link org.xtext.unina.xdstm.xDstm.Transition#isIs_preemptive <em>Is preemptive</em>}</li>
 *   <li>{@link org.xtext.unina.xdstm.xDstm.Transition#getTrigger <em>Trigger</em>}</li>
 *   <li>{@link org.xtext.unina.xdstm.xDstm.Transition#getCondition <em>Condition</em>}</li>
 *   <li>{@link org.xtext.unina.xdstm.xDstm.Transition#getActions <em>Actions</em>}</li>
 *   <li>{@link org.xtext.unina.xdstm.xDstm.Transition#getPar_instantiation <em>Par instantiation</em>}</li>
 * </ul>
 *
 * @see org.xtext.unina.xdstm.xDstm.XDstmPackage#getTransition()
 * @model
 * @generated
 */
public interface Transition extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.unina.xdstm.xDstm.XDstmPackage#getTransition_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.unina.xdstm.xDstm.Transition#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Requirements</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Requirements</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Requirements</em>' containment reference.
   * @see #setRequirements(requirements)
   * @see org.xtext.unina.xdstm.xDstm.XDstmPackage#getTransition_Requirements()
   * @model containment="true"
   * @generated
   */
  requirements getRequirements();

  /**
   * Sets the value of the '{@link org.xtext.unina.xdstm.xDstm.Transition#getRequirements <em>Requirements</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Requirements</em>' containment reference.
   * @see #getRequirements()
   * @generated
   */
  void setRequirements(requirements value);

  /**
   * Returns the value of the '<em><b>Source</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Source</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Source</em>' reference.
   * @see #setSource(Source)
   * @see org.xtext.unina.xdstm.xDstm.XDstmPackage#getTransition_Source()
   * @model
   * @generated
   */
  Source getSource();

  /**
   * Sets the value of the '{@link org.xtext.unina.xdstm.xDstm.Transition#getSource <em>Source</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Source</em>' reference.
   * @see #getSource()
   * @generated
   */
  void setSource(Source value);

  /**
   * Returns the value of the '<em><b>Exiting node</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Exiting node</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Exiting node</em>' reference.
   * @see #setExiting_node(ExitingNode)
   * @see org.xtext.unina.xdstm.xDstm.XDstmPackage#getTransition_Exiting_node()
   * @model
   * @generated
   */
  ExitingNode getExiting_node();

  /**
   * Sets the value of the '{@link org.xtext.unina.xdstm.xDstm.Transition#getExiting_node <em>Exiting node</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Exiting node</em>' reference.
   * @see #getExiting_node()
   * @generated
   */
  void setExiting_node(ExitingNode value);

  /**
   * Returns the value of the '<em><b>Destination</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Destination</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Destination</em>' reference.
   * @see #setDestination(Destination)
   * @see org.xtext.unina.xdstm.xDstm.XDstmPackage#getTransition_Destination()
   * @model
   * @generated
   */
  Destination getDestination();

  /**
   * Sets the value of the '{@link org.xtext.unina.xdstm.xDstm.Transition#getDestination <em>Destination</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Destination</em>' reference.
   * @see #getDestination()
   * @generated
   */
  void setDestination(Destination value);

  /**
   * Returns the value of the '<em><b>Entering node</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Entering node</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Entering node</em>' reference.
   * @see #setEntering_node(EnteringNodeAbs)
   * @see org.xtext.unina.xdstm.xDstm.XDstmPackage#getTransition_Entering_node()
   * @model
   * @generated
   */
  EnteringNodeAbs getEntering_node();

  /**
   * Sets the value of the '{@link org.xtext.unina.xdstm.xDstm.Transition#getEntering_node <em>Entering node</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Entering node</em>' reference.
   * @see #getEntering_node()
   * @generated
   */
  void setEntering_node(EnteringNodeAbs value);

  /**
   * Returns the value of the '<em><b>Is preemptive</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Is preemptive</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Is preemptive</em>' attribute.
   * @see #setIs_preemptive(boolean)
   * @see org.xtext.unina.xdstm.xDstm.XDstmPackage#getTransition_Is_preemptive()
   * @model
   * @generated
   */
  boolean isIs_preemptive();

  /**
   * Sets the value of the '{@link org.xtext.unina.xdstm.xDstm.Transition#isIs_preemptive <em>Is preemptive</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Is preemptive</em>' attribute.
   * @see #isIs_preemptive()
   * @generated
   */
  void setIs_preemptive(boolean value);

  /**
   * Returns the value of the '<em><b>Trigger</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Trigger</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Trigger</em>' attribute.
   * @see #setTrigger(String)
   * @see org.xtext.unina.xdstm.xDstm.XDstmPackage#getTransition_Trigger()
   * @model
   * @generated
   */
  String getTrigger();

  /**
   * Sets the value of the '{@link org.xtext.unina.xdstm.xDstm.Transition#getTrigger <em>Trigger</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Trigger</em>' attribute.
   * @see #getTrigger()
   * @generated
   */
  void setTrigger(String value);

  /**
   * Returns the value of the '<em><b>Condition</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Condition</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Condition</em>' attribute.
   * @see #setCondition(String)
   * @see org.xtext.unina.xdstm.xDstm.XDstmPackage#getTransition_Condition()
   * @model
   * @generated
   */
  String getCondition();

  /**
   * Sets the value of the '{@link org.xtext.unina.xdstm.xDstm.Transition#getCondition <em>Condition</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Condition</em>' attribute.
   * @see #getCondition()
   * @generated
   */
  void setCondition(String value);

  /**
   * Returns the value of the '<em><b>Actions</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Actions</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Actions</em>' attribute list.
   * @see org.xtext.unina.xdstm.xDstm.XDstmPackage#getTransition_Actions()
   * @model unique="false"
   * @generated
   */
  EList<String> getActions();

  /**
   * Returns the value of the '<em><b>Par instantiation</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Par instantiation</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Par instantiation</em>' attribute list.
   * @see org.xtext.unina.xdstm.xDstm.XDstmPackage#getTransition_Par_instantiation()
   * @model unique="false"
   * @generated
   */
  EList<String> getPar_instantiation();

} // Transition
