/**
 * generated by Xtext 2.13.0
 */
package org.xtext.unina.xdstm.xDstm;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Vertex</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.unina.xdstm.xDstm.XDstmPackage#getVertex()
 * @model
 * @generated
 */
public interface Vertex extends EObject
{
} // Vertex
