/*
 * generated by Xtext 2.13.0
 */
package org.xtext.unina.xdstm.ide

import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2
import org.xtext.unina.xdstm.XdstmRuntimeModule
import org.xtext.unina.xdstm.XdstmStandaloneSetup

/**
 * Initialization support for running Xtext languages as language servers.
 */
class XdstmIdeSetup extends XdstmStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new XdstmRuntimeModule, new XdstmIdeModule))
	}
	
}
