/*
 * generated by Xtext 2.13.0
 */
package org.xtext.unina.xdstm.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.unina.xdstm.ui.internal.XdstmActivator;

public class XdstmUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return XdstmActivator.getInstance().getInjector("org.xtext.unina.xdstm.Xdstm");
	}

}
